### ISSUE TITLE
Question about Saving Format

### ISSUE THREAD

**Issue by inoriln** [shuxiaoc/maxfuse#1]
Dear authors,

I am a clinical doctor who is just starting to learn Python. I apologize for asking what may seem like a very basic question. In "Example-2 of MaxFuse usage between RNA and Protein modality," we ultimately obtain the result called 'fusor'. Could you please advise me on how to save it? It seems that the conventional 'fusor.write' method doesn't quite work. What should I do? Thank you!

Best regards,

Yihao

**Comment by BokaiZhu** [comment]
Hi Yihao,

Thank you for being interested in the method. Typically for MaxFuse, the final result we use from the pipeline is either the final integrated CCA embedding, where one can use it to create UMAP plots (or similarly Tsne); or you can save out the matching information produced by pipeline (eg cell 1 from modality 1 is matched to cell 42 in modality 2).

We do not have a function to save out these results as they are many times customized per user's choice. We would suggest just saving out result as a dataframe if you would like to use them in the future. For example for the tutorial that you are following, you could save out the CCA embedding/matching result as a [pandas dataframe to a csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) (eg. transform the ```rna_cca ``` or ```full_matching ``` objects into a ```pandas.DataFrame``` obj and save them out as .csv).

Let me know if this explanation is straightforward enough.

Best,
Bokai

**Comment by BokaiZhu** [comment]
closing this issue for now, feel free to reopen it if you have more questions related to this.

**Comment by inoriln** [comment]
Thank you for your reply. It was very helpful for me and solved my problem.

Best regards,
Yihao

**Comment by ynanli** [comment]
Hi, 
Thanks for the great tool! Congrats!
I also have a similar question regarding saving the fusor file. 
I am wondering if it can be saved as a `pickle` object. But I'm not sure if it compromised the data.
I successfully created a pkl file as follows.
```
import pickle 
with open('fusor.pkl', "wb") as f:
    pickle.dump(fusor, f, pickle.HIGHEST_PROTOCOL)
```
The file can be loaded, but I am not super sure it is still the same model.

```
with open('fusor.pkl', 'rb') as f:
    fusor_2 = pickle.load(f)

fusor_2
Out[440]: <maxfuse.model.Fusor at 0x2214e513f70>

fusor == fusor_2
Out[441]: False

fusor
Out[442]: <maxfuse.model.Fusor at 0x2215271cf10>
```

Would you recommend to pickle the fusor? Or is it safer to stay with the pandas table?

Many thanks!

**Comment by BokaiZhu** [comment]
Hi Thanks for being interested in the tool, this is a good question. I would assume pickle would work but we have never tested this on our end so I do not know if this is entirely safe. Perhaps proceed with caution and let us know if there will be a problem. Good luck!
