### ISSUE TITLE
Solutions to Accelerate Computation Times for MaxFuse with Large-Scale Data Sets

### ISSUE THREAD

**Issue by ploughhh** [shuxiaoc/maxfuse#10]
Hi Chen,
I am currently exploring the use of MaxFuse for integration tasks involving CODEX and scRNA data, specifically aiming to apply this tool on large-scale datasets such as the HuBMAP CODEX intestinal data. This dataset encompasses millions of cells, which presents a significant computational challenge due to the lengthy processing times required.
Given the scale of the data I am working with, I would appreciate any advice or recommendations you might have on how to accelerate the integration process using MaxFuse. Are there any specific settings, parallel computing options, or hardware configurations that could potentially reduce the computation time?
Thank you for your assistance. I look forward to your suggestions and am eager to continue utilizing MaxFuse for extensive datasets.

**Comment by BokaiZhu** [comment]
Hi,

Thanks for being interested in the tool. Yes, speed is definitely important as larger and larger datasets are becoming more available.

In the current code, we have made MaxFuse running time and memory usage approx to a linear relation to the datasize, eg. here:

<img width="984" alt="Screenshot 2024-05-25 at 10 16 33 AM" src="https://github.com/shuxiaoc/maxfuse/assets/36682386/8c6cd106-ddb9-4bea-a4a0-2aca502cb051">

The parameter ```max_outward_size=8000``` controls the maximum cells used in each MaxFuse run (modality 1), and ```matching_ratio=4``` controls the cells used in each MaxFuse run (modality 2, eg. 4 * 8000).

By this way, in each batch run the time and memory are controlled, and the total run time should stay linear to the datasize increase.

Parallel computing is definitely something that could be helpful, but in the current iteration of the package, we did not implement such tricks. We encourage people to tweak the code and try!

Best,
Bokai
