### ISSUE TITLE
CODEX-scRNA integration data availability for the scRNA part

### ISSUE THREAD

**Issue by LianqingTong** [shuxiaoc/maxfuse#11]
Hello,
I'm Lianqing, a bioinformatics researcher at the LMU Munich. I'm highly interested in the MaxFuse method since the cross-modal integration method our group developed serves a very similar purpose of transferring cell-type annotations from one modality to another (usually scRNA to spatial proteomics) but using an algorithm based on Optimal Transport. Currently, we have tested the performance of our method on cell-typing of CODEX data with annotated scRNA data as reference, and we would like to apply MaxFuse to our dataset to compare performance, as well as apply our method to the dataset used in the MaxFuse article to see if it is easier to work with than ours. For that purpose, we examined the MaxFuse GitHub repository and would like to request the following files used in the CODEX part of the MaxFuse article:

1."/tonsil_v2/RNA/tonsil_rna_0510.txt": the scRNA count matrix.
2."/tonsil_v2/RNA/tonsil_rna_0510_meta.csv": containing the scRNA cell-type annotation.
3."/tonsil_v2/RNA/tonsil_rna_0510_names.csv": containing the scRNA gene names.

I see that the "for_match" file which is the processed CODEX data was already provided in a previous issue so that was really helpful!

Theoretically the scRNA data are available, however, I personally am not fluent enough in R to reproduce the scRNA preprocessing and I ran into warnings in the first step of Read10X (something like "10X data contains more than one type"). Therefore, I'd appreciate it a lot if the files above are available. They already contain all the information we need for our method.

Please feel free to designate a means of data transfer which is the most convenient for you. Many thanks in advance!

best regards,
Lianqing

**Comment by LianqingTong** [comment]
The errors regarding the Read10X were something like 10X data contains more than one type. Other things such as file paths and packages were of course adjusted accordingly. I'm pretty sure your code "tonsilrna_dataprep.R" should work but maybe at the time of your work with some slight tweaks to the data? Anyways for our purposes it's not necessary to add this extra step of reproduction. This comment's just to clarify the things a bit.

**Comment by BokaiZhu** [comment]
Hi Lianqing,
 
Thanks for being interested in our tool. Here is the dropbox link to all the input files we used in our manuscript (scRNA-seq Tonsil case): https://www.dropbox.com/scl/fo/4rq96uug0jesevjeqcosi/AJ6Z6K7b4ssSc7Cg2NfMdHo?rlkey=h3i1igej9uut5u5d3a04w6ay0&dl=0
 
Let me know if you have any problem accessing the data, or if you have any other question related to our method.
 
Best,
Bokai

**Comment by LianqingTong** [comment]
Great! Thanks for the swift response. That's all I need.
