### ISSUE TITLE
Fig. 5 Data Availability

### ISSUE THREAD

**Issue by pondandmoon** [shuxiaoc/maxfuse#15]
Hi authors,

I'm very interested in the MaxFuse algorithm and I'm attempting to reproduce the tri-modal integration task shown in Figure 5 of your paper. I've been following the procedures outlined in the CL_tri-integration.ipynb and SB_tri-integration.ipynb notebooks.
 I was wondering if it would be possible to provide the following data:
1. Count matrices for:
CODEX data
scRNA-seq data
scATAC-seq data
Gene Activity score for scATAC-seq

2. Related metadata information for each of these datasets

Thanks a lot!

**Comment by BokaiZhu** [comment]
Hi,

Thanks for being interested in the method. 

All the input and output files related to the script ```CL_tri-integration.ipynb``` can be find here in the folder: https://www.dropbox.com/scl/fo/nublgggr6d2lnox4mcyod/AP5SWIqtIWwW4RZ1hlyLAlA?rlkey=40wwxtvz7fcairfyo55210eog&dl=0
Let me know if you any questions related to that.

Note that the folder does not contain files related to ```SB_tri-integration.ipynb```; Some files related to that (CODEX) I don't have them immediately available: unfortunately the original server containing them is temporarily down right now; but if needed, I can regenerate them from source locally, it just need to take some extra time -- let me know if they are also needed for your case.

Best,
Bokai

**Comment by pondandmoon** [comment]
Thank you so much for your help! This is incredibly useful. Looking forward to seeing more of your amazing work!
