### ISSUE TITLE
Minimum number of CODEX markers to integrate with scRNA-Seq

### ISSUE THREAD

**Issue by PietroD** [shuxiaoc/maxfuse#16]
Thanks for the method.
As per the title, what is the minimum number of CODEX markers to integrate with scRNA-Seq.
We have a CODEX dataset with 20 markers, is it too low?

**Comment by BokaiZhu** [comment]
Hi,

Thanks for being interested in the method. There is no clear-cut number for the panel size to perform integration, and I think this should be evaluated case-by-case. For example, if you have a 50 ab CODEX panel, but you want to integrate it for a certain level of T cell populations with a similar scRNA-seq, but you only have one or two markers related to T cells. In this case, I would be cautious about the integration results. On the other hand, even if you only had 20 abs, these 20 abs do have good coverage of the information related to the biological question you want to answer via integration (eg. back to the T cell question, say you have 5-8 abs related somewhat to T cell biology), in this case, I would be more confident. So, at the end of the day, it really goes down to the goal that you are trying to achieve via cross-modality integration.

Best,
Bokai

**Comment by PietroD** [comment]
> Hi,
> 
> Thanks for being interested in the method. There is no clear-cut number for the panel size to perform integration, and I think this should be evaluated case-by-case. For example, if you have a 50 ab CODEX panel, but you want to integrate it for a certain level of T cell populations with a similar scRNA-seq, but you only have one or two markers related to T cells. In this case, I would be cautious about the integration results. On the other hand, even if you only had 20 abs, these 20 abs do have good coverage of the information related to the biological question you want to answer via integration (eg. back to the T cell question, say you have 5-8 abs related somewhat to T cell biology), in this case, I would be more confident. So, at the end of the day, it really goes down to the goal that you are trying to achieve via cross-modality integration.
> 
> Best, Bokai

Makes sense. Thanks a lot
