### ISSUE TITLE
CODEX data availability

### ISSUE THREAD

**Issue by JiawenChenn** [shuxiaoc/maxfuse#4]
Hi authors,

I have recently read this paper and found the CODEX analysis super interesting. I would like to replicate the analysis in figure 4 (prepare_gc_related.ipynb). Is it possible to share with me the these two datasets:
/home/bkzhu/super_mario/tonsil_v2/Codex/FCS_output_DeepCell_extOnly/formatch_clusters_x28_y715V2_xy.csv
/home/bkzhu/super_mario/tonsil_v2/Codex/tiled/GC_mask.tif

Thanks a lot!

**Comment by BokaiZhu** [comment]
Hi thanks for being interested. For the two file requested, please see this link: https://www.dropbox.com/sh/c779k9v64xzkua4/AAAyeVp96W8OBS242ybRSbO4a?dl=0
Let me know if there is any questions.

**Comment by JiawenChenn** [comment]
Thanks for the reply. That's really helpful!
