### ISSUE TITLE
save fusor object

### ISSUE THREAD

**Issue by mcaponegro** [shuxiaoc/maxfuse#6]
Hi,

thanks again, the package is working well. Python is not my first coding language. Any tips on how to save/load the final fusor object?

I have tried pickle but get the following error:
```
# 'fusor' is the maxfuse object with all arrays and data
import pickle
file_name = "fusor_model.pkl"
with open(file_name, 'wb') as file:
    pickle.dump(fusor, file))
file.close()
```

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: Can't pickle local object 'Fusor._fit_svd_on_full_data.<locals>.<lambda>'
```

Thanks

Alos, any tips on how to combine metdata from the original anndata objects into the full matched dataframe, or the final cca_adata?

**Comment by mcaponegro** [comment]
This works for individual obs columns 

```
cca_adata.obs['cell_ID'] = list(np.concatenate((sc_adata.obs.Barcode,
                                                  protien_adata.obs.cell_ID[full_matching[1]]), axis = 0))    
```

**Comment by BokaiZhu** [comment]
Hi and sorry for the delayed response, somehow missed some recent issues in the github forum. Hope the delay was not troubling for you.

For the saving out / reformatting etc of the results, would ```pandas``` and the related functionality fit your purpose? Eg everything would be similarly structured as ```data.frame``` as in ```R``` and final output can be saved as .```csv```. You just need to extract the results from ```.fusor``` out as either ```np``` or ```list``` and format back to a ```pd.df```. Let me know if there is any thing that is not clear. For pandas here might be a good starting point if you are not familiar: https://pandas.pydata.org/docs/user_guide/10min.html

**Comment by mcaponegro** [comment]
no worries. yes I was able to piece it together. Still unable to save the model but I have not tried recently. I can update soon.

**Comment by BokaiZhu** [comment]
Sounds good let us know if there's more problem.
