### ISSUE TITLE
Suitability for integrating scRNA-seq and CosMx SMI 100 panel data

### ISSUE THREAD

**Issue by hiiiyilingzhang** [shuxiaoc/maxfuse#7]
Dear Authors,

Thanks for the development of MaxFuse. I an interested in apply the model to integrate scRNA-seq and CosMx SMI data. Our CosMx SMI use 95 RNA target panel for characterization, I am not sure if its a proper practice. I would greatly appreciate your insights!

Best,
Elaine

**Comment by BokaiZhu** [comment]
Hi Elaine, sorry for the delayed response, just saw this right now.

In terms of matching between CosMx to scRNAseq, although not extensively benchmarked like cases in the publication, we do have some internal testing on such cases and they all seem to give reasonable results. Cases we have internally played around include matching between merfish with 250 genes to scRNA-seq, or CosMx with 1k gene panel to scRNA-seq. For the actual running process, we don't have any specific changes that need to be made to the code, but of course, the choice of parameters etc is more dataset depended. 

Let me know if you would like to have more insights. Generally I would just suggest to give a shoot and see if the results are satisfying; Meanwhile feel free to use other methods, for gene-gene matching potentially other methods can be tried too.

**Comment by hiiiyilingzhang** [comment]
Hi Bokai, 

Thanks for your kind reply and suggestions. I feel like our situation is really suitable for using the model, so I will have a try. Much appreciate for developing the tool! 

I'll close the issue and Happy CNY!

Elaine
