### ISSUE TITLE
Guidance on Gene Conversion for Broad-Spectrum Antibodies like PanCK

### ISSUE THREAD

**Issue by inoriln** [shuxiaoc/maxfuse#8]
Hello,

I am currently working on a maxfuse-related project and utilizing the protein_gene_conversion.csv file for protein-gene conversation. In my dataset, I use broad-spectrum antibodies, such as PanCK, which can interact with multiple types of Cytokeratins. it is important since PanCK is specifically expressed in brain metastatic tumor cells

I'm seeking clarification on how to correctly convert these broad-spectrum antibodies into gene identifiers in the protein_gene_conversion.csv file. Specifically, should I list all the genes corresponding to the proteins that PanCK can potentially react with? For example, PanCK interacts with several Cytokeratins; should I include all relevant Cytokeratin genes like KRT8, KRT18, etc.?

Any guidance on how to approach this in the conversion file would be greatly appreciated.

Thank you!
Yihao

**Comment by BokaiZhu** [comment]
Hi Yihao,

Sorry for the late reply just saw this.

You can modify the ```protein_gene_conversion.csv``` file to include more antibodies.

For proteins related to multiple genes you can do this:

<img width="630" alt="Screenshot 2024-05-25 at 10 04 30 AM" src="https://github.com/shuxiaoc/maxfuse/assets/36682386/3b95aed2-b7fe-4179-b922-e9e77d35fdcb">


eg. for Galectin, the RNAs have multiple genes separated by ```/```. This means for one protein, all these RNAs will be treated as the linked features.

Let me know if this clarifies the question, thanks!

Best,
Bokai
