### ISSUE TITLE
Integrating spatial proteomics and transcriptomics: When cells of the same type are in different locations

### ISSUE THREAD

**Issue by ssaintsoon** [shuxiaoc/maxfuse#9]
Hello,

I'm impressed what MaxFuse can do and interested in exploring it's capabilities in integrating multi-omics datasets, particularly in the context of spatial proteomics and transcriptomics like CODEX and RNA-seq. One question I have is regarding the potential differences between infiltrating CD8 T cells (located within the tumor) and non-infiltrating CD8 T cells. If the protein marker expressions are indistinguishable between these two cell populations, does MaxFuse effectively match cells across different modalities?

I greatly appreciate the authors' contributions and the opportunity to delve into this exciting field.
Thank you!

Sincerely,
Kwon

**Comment by BokaiZhu** [comment]
Hi Kwon,

Sorry for the late reply just saw the question. This is an interesting question. Based on your description, one of the modalities (CODEX) has ZERO information to distinguish these cells (no difference in all proteins at all). In this case I don't see MaxFuse would work well for matching these cells differently to the scRNA-seq data, as MaxFuse does not 'increase' andy information but only use available info from the existing datasets. Let me know if you have more questions and happy to discuss.

Best,
Bokai

**Comment by ssaintsoon** [comment]
Hi Bokai,

Thanks for your kind response. This suggests that separate markers may be needed to distinguish infiltrating/non-infiltrating T cells. Although I haven't assessed the changes in CD8 levels at different sites (inside or outside of the tumor), it looks quite heterogeneous, and I doubt there will be significant differences. I think that adding markers involved in chemoattraction, such as CXCR5 might be a solution.

Once again, thank you for your response, I'll close this issue now. Hope you have a great day!

Best,
Kwon
